version: '3'

services:
  truffle:
    build: .
    depends_on:
      - ganache
    networks: 
      - network
    volumes:
      - ./contracts:/truffle/contracts
      - ./app/src/contracts:/truffle/app/src/contracts
  ganache:
    image: trufflesuite/ganache-cli
    restart: unless-stopped
    networks: 
      - network
    ports:
      - 8545:8545
      - 8546:8546
    command: -d --fork "http://192.168.1.111:8547@10062698" --gasLimit "90000000" --mnemonic "toss seven aerobic pledge lumber yard evil benefit title duty winter initial" --networkId "999" --block-time "5"

networks:
  network:

# Revisit this:
# https://github.com/lzhou1110/drizzle-truffle-ganache-docker-box/blob/master/docker-compose-dev.yml

